module.exports = {
  clearMocks: true,
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.d.ts",
    "!src/**/*.test.ts",
    "!src/**/*.spec.ts",
    "!src/**/index.ts",
    "!src/server.ts",
    "!src/scripts/**",
    "!src/config/app.ts",
    "!src/**/*.routes.ts",
    "!src/**/*.constants.ts",
    "!src/**/dto/registrar.*.types.ts",
    "!src/**/dto/resposta.localidade.types.ts",
    "!src/**/dto/resposta.nacionalidade.types.ts",
    "!src/**/dto/resposta.opcoes-academicas.types.ts",
    "!src/shared/constants/**",
    "!src/shared/types/**",
    "!src/shared/errors/**",
    "!src/modules/exemplo/**",
    "!src/config/db.ts",
    "!src/config/logger.ts",
    "!src/shared/middlewares/papeis.middleware.ts",
    "!src/shared/middlewares/tratamento-erros.middleware.ts",
  ],
  coverageReporters: ["text", "lcov", "json-summary"],
  moduleFileExtensions: ["ts", "js", "json"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  setupFiles: ["<rootDir>/jest.setup.js"],
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/*.test.ts", "<rootDir>/tests/**/*.test.ts"],
  transform: {
    "^.+\\.ts$": "babel-jest",
  },
};
